version: "3.9"

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    network_mode: host
    volumes:
      - node_red_data:/data

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - homeassistant_data:/config

volumes:

  node_red_data:

  homeassistant_data:
